config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :products do
    resources :comments
  end
  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  root 'products#index'

	get 'static_pages/thank_you'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'

  resources :payments

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <!--navbar starts here-->
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div><!-- Collect the nav links, forms, and other content for toggling -->

      <div class="collapse navbar-collapse navbar-ex1-collapse mynav">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", static_pages_landing_page_path %></li>
          <li><a href="#">About</a></li>
          <li><%= link_to "Contact", static_pages_contact_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
       </ul>
       <ul class="nav navbar-nav pull-right">
         <li>
         <% if user_signed_in? %>
           <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
         <% else %>
           <%= link_to('Login', new_user_session_path) %>
         <% end %>
         </li>
       </ul>

       <%= form_tag("/products",method: :get, class: "navbar-form navbar-right") do -%>
       		<div class="form-group">
       			 <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
       		</div>
       			 <%= submit_tag("Search", class: "btn btn-default") %>
       		<% end -%>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <div class="container-fluid">
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>
  </div>


  <%= yield %>

  <footer>
    <div class="container-fluid foot">
      &copy; Slavko Galic 2016
    </div>
  </footer>
 </body>
</html>